name: Run tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
  
    strategy:
      matrix: 
        node-version: [18.x, 16.x, 14.x]
        
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm test
