name: Run tests
on: 
  push:
    branches:
    - 'TEST-SCRIPTS-NO-DESIGN-YET'

  pull_request:
    branches:
    - 'TEST-SCRIPTS-NO-DESIGN-YET'
jobs:
  tests:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with: 
          node-version: 16.18
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
      - run: npm test
